-- Velli School Supabase setup
-- Run this in Supabase SQL Editor for the cleaned project.
-- SAT, news/articles, and Supabase Auth admin tables are intentionally omitted.

create extension if not exists pgcrypto;

-- Clean old objects from the copied project, if they exist.
drop table if exists public.news cascade;
drop table if exists public.sat_exams cascade;
drop table if exists public.sat_exam_results cascade;
drop table if exists public.sat_placement_test_results cascade;
drop table if exists public.admin_data cascade;

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null unique,
  password text not null,
  approved boolean not null default true
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null unique,
  password text not null,
  phone text,
  parent_phone text,
  parent_name text,
  level text,
  image_url text,
  student_school text,
  student_purpose text,
  placement_test boolean not null default false,
  stock boolean not null default false
);

create table if not exists public.levels (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null unique,
  description text
);

create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  file_url text,
  pass_score numeric not null default 0,
  total_score numeric,
  duration numeric not null default 1,
  level text,
  exam_file text,
  unit text
);

create table if not exists public.practice_exam (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  exam_file text,
  pass_score numeric not null default 0,
  total_score numeric,
  duration numeric not null default 1,
  level text,
  unit text
);

create table if not exists public.placement_test (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  exam_file text,
  file_url text,
  pass_score numeric not null default 0,
  total_score numeric,
  duration numeric not null default 1,
  level text
);

create table if not exists public."approved-exams" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  student_id bigint,
  title text,
  level text,
  duration numeric,
  pass_score numeric,
  file_url text,
  locked boolean not null default false,
  student_name text,
  sended boolean default false
);

create table if not exists public."taken-exams" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  student_id bigint not null,
  exam_count integer not null default 0,
  practice_count integer not null default 0,
  unique (student_id)
);

create table if not exists public.student_results (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  student_id bigint,
  student_name text,
  student_level text,
  exam_name text,
  student_score numeric not null default 0,
  reading_score numeric default 0,
  listening_score numeric default 0,
  grammar_score numeric default 0,
  vocabulary_score numeric default 0,
  reading_count integer default 0,
  listening_count integer default 0,
  grammar_count integer default 0,
  vocabulary_count integer default 0,
  finish_time integer default 0
);

create table if not exists public.student_practice_results (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  student_id bigint,
  student_name text,
  name text,
  student_level text,
  exam_name text,
  score numeric not null default 0,
  total_questions integer default 0,
  unit text,
  finish_time integer default 0
);

create table if not exists public.placement_test_results (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  student_id bigint,
  student_name text,
  total_score numeric not null default 0,
  listening numeric default 0,
  reading numeric default 0,
  grammar numeric default 0,
  vocabulary numeric default 0,
  listening_count integer default 0,
  reading_count integer default 0,
  grammar_count integer default 0,
  vocabulary_count integer default 0,
  finish_time integer default 0
);

do $$
begin
  if to_regclass('public.students') is not null then
    if to_regclass('public."approved-exams"') is not null
      and not exists (select 1 from pg_constraint where conname = 'approved_exams_student_id_fkey') then
      alter table public."approved-exams"
        add constraint approved_exams_student_id_fkey
        foreign key (student_id) references public.students(id) on delete cascade;
    end if;

    if to_regclass('public."taken-exams"') is not null
      and not exists (select 1 from pg_constraint where conname = 'taken_exams_student_id_fkey') then
      alter table public."taken-exams"
        add constraint taken_exams_student_id_fkey
        foreign key (student_id) references public.students(id) on delete cascade;
    end if;

    if to_regclass('public.student_results') is not null
      and not exists (select 1 from pg_constraint where conname = 'student_results_student_id_fkey') then
      alter table public.student_results
        add constraint student_results_student_id_fkey
        foreign key (student_id) references public.students(id) on delete cascade;
    end if;

    if to_regclass('public.student_practice_results') is not null
      and not exists (select 1 from pg_constraint where conname = 'student_practice_results_student_id_fkey') then
      alter table public.student_practice_results
        add constraint student_practice_results_student_id_fkey
        foreign key (student_id) references public.students(id) on delete cascade;
    end if;

    if to_regclass('public.placement_test_results') is not null
      and not exists (select 1 from pg_constraint where conname = 'placement_test_results_student_id_fkey') then
      alter table public.placement_test_results
        add constraint placement_test_results_student_id_fkey
        foreign key (student_id) references public.students(id) on delete cascade;
    end if;
  end if;
end $$;

insert into public.admin_users (email, password, approved)
values ('admin@familyschool.az', 'Family135!', true)
on conflict (email) do update
set password = excluded.password,
    approved = excluded.approved;

insert into public.levels (name, description)
values
  ('A1', 'Beginner'),
  ('A2', 'Elementary'),
  ('B1', 'Intermediate'),
  ('B1+', 'Upper intermediate'),
  ('B2', 'Upper intermediate'),
  ('C1', 'Advanced')
on conflict (name) do nothing;

insert into storage.buckets (id, name, public)
values
  ('uploads', 'uploads', true),
  ('student-images', 'student-images', true)
on conflict (id) do update set public = excluded.public;

alter table if exists public.admin_users disable row level security;
alter table if exists public.students disable row level security;
alter table if exists public.levels disable row level security;
alter table if exists public.exams disable row level security;
alter table if exists public.practice_exam disable row level security;
alter table if exists public.placement_test disable row level security;
alter table if exists public."approved-exams" disable row level security;
alter table if exists public."taken-exams" disable row level security;
alter table if exists public.student_results disable row level security;
alter table if exists public.student_practice_results disable row level security;
alter table if exists public.placement_test_results disable row level security;

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant all on tables to anon, authenticated;
alter default privileges in schema public grant all on sequences to anon, authenticated;

drop policy if exists "app_storage_read" on storage.objects;
drop policy if exists "app_storage_insert" on storage.objects;
drop policy if exists "app_storage_update" on storage.objects;
drop policy if exists "app_storage_delete" on storage.objects;

create policy "app_storage_read"
on storage.objects for select
to anon, authenticated
using (bucket_id in ('uploads', 'student-images'));

create policy "app_storage_insert"
on storage.objects for insert
to anon, authenticated
with check (bucket_id in ('uploads', 'student-images'));

create policy "app_storage_update"
on storage.objects for update
to anon, authenticated
using (bucket_id in ('uploads', 'student-images'))
with check (bucket_id in ('uploads', 'student-images'));

create policy "app_storage_delete"
on storage.objects for delete
to anon, authenticated
using (bucket_id in ('uploads', 'student-images'));
